// AST1.h -- LAYER 2, the C++ layer, namespace `cxx`.
//
// Declares only what C++ adds to C: reference and class types, classes and
// their members, qualified names, member access, `this` and the free store.
// Everything else is used directly from cc.  See AST.h for the layering model.
//
// C++98 only.

#ifndef AST1_H
#define AST1_H

#include <cstddef>
#include <string>
#include <vector>
#include <iostream>

#include "AST.h"

namespace cxx {

// The SAME types as in cc, not copies -- pulled in so this layer can spell
// them unqualified.
using cc::Type;
using cc::BuiltinType;
using cc::PointerType;
using cc::Decl;
using cc::VarDecl;
using cc::Function;

// `protected` differs from `private` only once inheritance exists.
enum Access { ACC_Public, ACC_Private, ACC_Protected };
const char *accessText(Access a);

// --- Types added by C++ -----------------------------------------------

struct ReferenceType : public Type {
    Type *base;
    ReferenceType(Type *b) : base(b) {}
    ~ReferenceType() { delete base; }
    void print(int indent);
};

// bool -- C89 has none, so it is C++'s, exactly like T& and class types.
//
// It is a node rather than another cc::BuiltinKind because that enum is the C
// layer's, and adding to it would put a C++ type in C's table.  Nothing is
// lost by keeping it out: bool promotes to int on entering any arithmetic, so
// the rank table never needs to name it -- only the edges do, where a value is
// converted to or from bool.
struct BoolType : public Type {
    void print(int indent);
};

struct ClassType : public Type {
    std::string className;
    ClassType(const std::string &n) : className(n) {}
    void print(int indent);
};

// --- Declarations added by C++ ----------------------------------------

// A declaration with an access level and an owning class, which a plain
// cc::VarDecl has neither of.
struct FieldDecl : public Decl {
    Type *type;
    std::string name;
    Access access;
    std::string ownerClass;
    FieldDecl(Type *t, const std::string &n, Access a)
        : type(t), name(n), access(a) {}
    ~FieldDecl() { delete type; }
    void print(int indent);
};

// One entry in a constructor's initialiser list: x(1) or Base(a, b).  Which
// kind it is, is decided by the semantic pass and recorded in `isBase`.
struct MemberInit {
    std::string name;
    std::vector<cc::Expr*> args;
    bool isBase;
    int line;
    int col;
    cc::Function *resolvedCtor;         // chosen by the semantic pass; not owned
    MemberInit() : isBase(false), line(0), col(0), resolvedCtor(0) {}
};

// A method IS a function that also knows its access, its class and whether it
// is virtual -- so it derives from cc::Function instead of restating it.
// Constructors and destructors are methods too: no return type and a special
// name, but otherwise nothing different.
struct MethodDecl : public Function {
    Access access;
    std::string ownerClass;
    // Written `virtual`, or inherited by overriding a base virtual -- so the
    // semantic pass sets this as well as the parser.
    bool isVirtual;
    MethodDecl *overrides;      // 0 when this overrides nothing
    bool isConstructor;
    bool isDestructor;
    // `int get() const` -- the const applies to *this, so the method promises
    // not to modify the object, and only such a method may be called on one.
    bool isConstMethod;
    // Generated by the compiler rather than written: a destructor a class
    // needed because it owns something destructible.  Advice aimed at code the
    // user wrote should stay quiet about it.
    bool isImplicit;
    std::vector<MemberInit> memberInits;    // constructors only

    MethodDecl(Type *r, const std::string &n, Access a)
        : Function(r, n), access(a), isVirtual(false), overrides(0),
          isConstructor(false), isDestructor(false), isConstMethod(false),
          isImplicit(false) {}
    ~MethodDecl();
    // Only the first printed line differs from a plain function.
    void printSignature(int indent);
    void printBodyPrefix(int indent);
};

// SINGLE inheritance by design: with one base the derived object is the base
// object with fields appended, so an upcast is a no-op and the vptr is shared.
// The parser rejects a second base by name rather than as a syntax error.
struct ClassDecl : public Decl {
    std::string name;
    std::string baseName;       // empty when the class has no base
    Access baseAccess;          // public/private/protected inheritance
    ClassDecl *base;            // resolved by the semantic pass; not owned
    std::vector<Decl*> members;
    // Aliases into `members`, which owns them.  Constructors are indexed apart
    // because they share one name; they are selected by argument count.
    std::vector<MethodDecl*> ctors;
    MethodDecl *dtor;               // 0 when the class declares none
    // The functions granted access to the private parts, by NAME AND
    // SIGNATURE: `friend int peek(Box);` grants nothing to `peek(Box, int)`.
    // Aliases only -- a prototype that has no definition to belong to is kept
    // in friendProtos, which is what this class deletes.
    std::vector<cc::Function*> friends;
    std::vector<cc::Function*> friendProtos;
    ClassDecl(const std::string &n)
        : name(n), baseAccess(ACC_Public), base(0), dtor(0) {}
    ~ClassDecl();
    void print(int indent);
};

// --- Qualified name  A::B ---------------------------------------------
struct QualifiedName : public cc::ASTNode {
    std::vector<std::string> parts;
    QualifiedName() {}
    void print(int indent);
};

// --- Expressions added by C++ -----------------------------------------
// The cc:: forms are used directly, not redeclared.  Only new forms appear
// here, each deriving from cc::Expr so both share one tree:  (a.b + 1) * 2

struct MemberAccessExpr : public cc::Expr {
    cc::Expr *base;
    std::string member;
    bool isArrow;
    MemberAccessExpr(cc::Expr *b, const std::string &m, bool arrow)
        : base(b), member(m), isArrow(arrow) {}
    ~MemberAccessExpr() { delete base; }
    void print(int indent);
};

struct ThisExpr : public cc::Expr {
    void print(int indent);
};

// true and false
struct BoolExpr : public cc::Expr {
    bool value;
    BoolExpr(bool v) : value(v) {}
    void print(int indent);
};

// T(args) -- an unnamed object built where it stands.  `return V(x + o.x);`
// is the ordinary body of an overloaded operator, so this is not a luxury.
struct TempExpr : public cc::Expr {
    Type *type;                         // owned
    std::vector<cc::Expr*> args;        // owned
    cc::Function *resolvedCtor;         // chosen by the semantic pass; not owned
    TempExpr(Type *t) : type(t), resolvedCtor(0) {}
    ~TempExpr();
    void print(int indent);
};

struct NewExpr : public cc::Expr {
    Type *allocType;
    // new T[n]: the count, owned, and 0 for the single-object form.  It is an
    // EXPRESSION, not a constant -- the bound of a heap array is a value the
    // program computes, which is the whole reason to want one.
    cc::Expr *count;
    std::vector<cc::Expr*> args;
    cc::Function *resolvedCtor;         // chosen by the semantic pass; not owned
    NewExpr(Type *t) : allocType(t), count(0), resolvedCtor(0) {}
    ~NewExpr();
    void print(int indent);
};

struct DeleteExpr : public cc::Expr {
    cc::Expr *operand;
    // delete[] -- it must match the new that made the block, and here that is
    // checked rather than assumed: the allocator records which form was used.
    bool isArray;
    DeleteExpr(cc::Expr *e) : operand(e), isArray(false) {}
    ~DeleteExpr() { delete operand; }
    void print(int indent);
};

} // namespace cxx

#endif
