//
//  main.cpp
//  Compiler++
//
//  Created by G. R. Akhtar on 29/08/2026.
//
//  Reads a source file and runs it through the front end:
//      Parser -> Semantic -> Layout -> Lower, reporting via Diagnostics.
//
//  `usage()` below is the one statement of what the arguments are; this
//  comment used to be the other, and the two had already drifted apart.
//
//  A .cxb given as the input is loaded and run directly, with no compiling --
//  which is what makes the output a real artifact rather than a print-out.
//
//  There is no default input.  Running an Xcode scheme with no arguments now
//  prints usage instead of compiling one developer's scratch file; pass a path
//  via Product > Scheme > Edit Scheme > Arguments.
//
//  Exit status: 0 clean, 1 errors, 2 the arguments or the file, 3 the VM
//  stopped the program.
//
//  C++98 only.
//

#include <cstddef>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

#include "AST.h"
#include "AST1.h"
#include "Diagnostics.h"
#include "Bytecode.h"
#include "CodeGen.h"
#include "IR.h"
#include "Layout.h"
#include "Lexer.h"
#include "Lower1.h"
#include "Parser.h"
#include "Parser1.h"
#include "Semantic.h"
#include "VM.h"

// Windows translates '\n' into "\r\n" on a text-mode stream, so the compiler
// wrote CRLF there while every golden file is LF -- and the whole suite failed
// against a correct compiler, 120 cases out of 120, which reads as a compiler
// fault and is not.  .gitattributes settled this for the bytes going IN; this
// settles it for the bytes coming out, so the compiler writes '\n' on every
// platform it builds on and the suites compare byte for byte wherever they run.
//
// It has to run before anything is written, which is why it is main's first
// statement.  The .cxb path never needed it: Bytecode.cpp opens those streams
// with ios::binary already.
#if defined(_WIN32)
#include <fcntl.h>
#include <io.h>
static void writeUntranslatedOutput() {
    _setmode(_fileno(stdout), _O_BINARY);
    _setmode(_fileno(stderr), _O_BINARY);
}
#else
static void writeUntranslatedOutput() { }
#endif

// The one statement of what the arguments are.  An unrecognised switch used to
// become the input path, so `--help` was reported as a file that could not be
// opened -- and with nothing to report at all, the compiler read an absolute
// path inside one developer's home directory.
static void usage(std::ostream &out) {
    out << "usage: compilerpp [options] <file.cpp | file.cxb>\n"
        << "\n"
        << "  -ast      print the syntax tree\n"
        << "  -layout   print each class's object layout and vtable\n"
        << "  -ir       print the lowered intermediate representation\n"
        << "  -bc       print the generated bytecode\n"
        << "  -run      compile and run, returning the program's own result\n"
        << "  -o FILE   write the compiled image to FILE, a .cxb object file\n"
        << "  -q        diagnostics only, no banner\n"
        << "  -h        print this and stop\n"
        << "\n"
        << "A .cxb given as the input is run directly, with nothing compiled.\n"
        << "\n"
        << "Exit status: 0 clean, 1 errors, 2 the arguments or the file,\n"
        << "3 the VM stopped the program.\n";
}

static bool readFile(const std::string &path, std::string &out) {
    std::ifstream in(path.c_str());
    if (!in) return false;
    std::ostringstream ss;
    ss << in.rdbuf();
    out = ss.str();
    return true;
}

// Diagnostics read better without the path.
static std::string baseName(const std::string &path) {
    const std::string::size_type slash = path.find_last_of('/');
    return (slash == std::string::npos) ? path : path.substr(slash + 1);
}

int main(int argc, char **argv) {
    writeUntranslatedOutput();

    bool showAst = false;
    bool showLayout = false;
    bool showIR = false;
    bool showBC = false;
    bool doRun = false;
    bool quiet = false;
    std::string path;
    std::string outPath;

    for (int i = 1; i < argc; ++i) {
        const std::string arg = argv[i];
        if      (arg == "-ast")    showAst = true;
        else if (arg == "-layout") showLayout = true;
        else if (arg == "-ir")     showIR = true;
        else if (arg == "-bc")     showBC = true;
        else if (arg == "-run")    doRun = true;
        else if (arg == "-q")      quiet = true;
        else if (arg == "-h" || arg == "--help") { usage(std::cout); return 0; }
        else if (arg == "-o") {
            // `-o` last on the line used to fall through and become the input
            // path, so the compiler reported "-o" as a file it could not open.
            if (i + 1 >= argc) {
                std::cerr << "-o needs a file to write" << std::endl;
                return 2;
            }
            outPath = argv[++i];
        }
        else if (!arg.empty() && arg[0] == '-') {
            std::cerr << "Unknown option: " << arg << std::endl;
            usage(std::cerr);
            return 2;
        }
        // A second input silently replaced the first, so a mistyped option
        // took the place of the file it was written beside.
        else if (!path.empty()) {
            std::cerr << "Only one input file, and '" << path << "' is already it: "
                      << arg << std::endl;
            return 2;
        }
        else path = arg;
    }
    if (path.empty()) {
        usage(std::cerr);
        return 2;
    }

    std::string source;
    if (!readFile(path, source)) {
        std::cerr << "Cannot open input file: " << path << std::endl;
        return 2;
    }

    // A .cxb is already compiled: load it and run it.
    if (path.size() > 4 && path.substr(path.size() - 4) == ".cxb") {
        Image image;
        std::string err;
        if (!image.read(path, err)) {
            std::cerr << err << std::endl;
            return 2;
        }
        if (showBC) {
            if (!quiet) std::cout << "=== BYTECODE: " << baseName(path) << " ===" << std::endl;
            image.disassemble();
        }
        if (!doRun) return 0;
        VM vm;
        bool ok = false;
        const vmword result = vm.run(image, ok);
        std::cout.flush();
        if (!ok) {
            std::cerr << baseName(path) << ": runtime error: " << vm.errorMessage() << std::endl;
            return 3;
        }
        if (!quiet) std::cout << "main returned " << result << std::endl;
        return 0;
    }

    Diagnostics diag(baseName(path));

    // parseTranslationUnit() is the C layer's, but every hook it calls is
    // virtual, so a cxx::Parser parses the C++ forms through the same loop.
    // <iostream> is written in this language, so "including" it is prepending
    // it.  The lines it occupies are subtracted from every diagnostic, so the
    // user still sees their own numbering.
    int preludeLines = 0;
    const std::string prelude = preludeFor(source, preludeLines);
    if (!prelude.empty()) {
        source = prelude + source;
        diag.setLineOffset(preludeLines);
    }

    // #define is a textual substitution, so it happens before the first token.
    source = expandDefines(source, diag);

    cxx::Parser parser(source, diag);
    std::vector<cc::Decl*> unit = parser.parseTranslationUnit();

    // Analysis runs even after syntax errors, and BEFORE printing: it writes
    // conclusions back into the tree (virtualness, overrides) that a dump taken
    // earlier would not show.
    {
        SemanticAnalyzer sem(diag);
        sem.analyze(unit);

        if (showAst) {
            if (!quiet) std::cout << "=== SYNTAX TREE: " << baseName(path) << " ===" << std::endl;
            // The prelude is compiler-supplied, so a dump of "the program"
            // means the user's own declarations, not <iostream>'s.
            for (std::size_t i = 0; i < unit.size(); ++i) {
                if (unit[i]->line <= preludeLines) continue;
                unit[i]->print(0);
            }
            std::cout << std::endl;
        }

        // Runs ALWAYS, not only when printing: it enforces constraints of its
        // own, and a diagnostic must not depend on a debug flag.
        Layout layout(diag);
        layout.computeAll(sem.classMap());
        if (showLayout) {
            if (!quiet) std::cout << "=== OBJECT LAYOUT: " << baseName(path) << " ===" << std::endl;
            layout.print();
        }

        // Only over a tree that survived analysis: lowering unresolved names
        // would produce nonsense rather than a better diagnostic.
        if ((showIR || showBC || doRun || !outPath.empty()) && !diag.hadError()) {
            IRModule module;
            {
                cxx::Lowering lower(module, layout, diag, sem.classMap());
                lower.lowerClasses();
                lower.lowerUnit(unit);
            }
            if (showIR) {
                if (!quiet) std::cout << "=== IR: " << baseName(path) << " ===" << std::endl;
                module.print();
            }

            if ((showBC || doRun || !outPath.empty()) && !diag.hadError()) {
                Image image;
                CodeGen gen(diag);
                gen.generate(module, image);

                if (showBC) {
                    if (!quiet) std::cout << "=== BYTECODE: " << baseName(path) << " ===" << std::endl;
                    image.disassemble();
                }
                if (!outPath.empty() && !diag.hadError()) {
                    std::string err;
                    if (!image.write(outPath, err)) {
                        std::cerr << err << std::endl;
                        for (std::size_t i = 0; i < unit.size(); ++i) delete unit[i];
                        return 2;
                    }
                    if (!quiet) std::cout << "wrote " << outPath << std::endl;
                }
                if (doRun && !diag.hadError()) {
                    if (!quiet) std::cout << "=== RUN: " << baseName(path) << " ===" << std::endl;
                    VM vm;
                    bool ok = false;
                    const vmword result = vm.run(image, ok);
                    if (!ok) {
                        std::cout.flush();
                        std::cerr << baseName(path) << ": runtime error: "
                                  << vm.errorMessage() << std::endl;
                        for (std::size_t i = 0; i < unit.size(); ++i) delete unit[i];
                        return 3;
                    }
                    std::cout.flush();
                    if (!quiet) {
                        std::cout << "main returned " << result
                                  << "  (" << vm.stepCount() << " steps)" << std::endl;
                    }
                    for (std::size_t i = 0; i < unit.size(); ++i) delete unit[i];
                    return 0;
                }
            }
        }
    }

    if (!quiet) diag.printSummary();

    for (std::size_t i = 0; i < unit.size(); ++i) delete unit[i];
    return diag.hadError() ? 1 : 0;
}
